Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace The_Bread_Pit.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Area("Admin")]
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Areas/Employee/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace The_Bread_Pit.Areas.Employee.Controllers
{
    public class HomeController : Controller
    {
        [Area("Employee")]
        [Authorize(Roles = "Employee")]
        public IActionResult Index()
        {
            return View();
        }            
    }
}

Areas/User/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace The_Bread_Pit.Areas.User.Controllers
{
    public class HomeController : Controller
    {
        [Area("User")]
        [Authorize(Roles = "User")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Areas/User/Controllers/ProduktController.cs
using Microsoft.AspNetCore.Mvc;
using The_Bread_Pit.Models;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using System;

namespace The_Bread_Pit.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "User")]
    public class ProduktController : Controller
    {
        private TheBreadPitContext context;
        private IWebHostEnvironment? _environment;


        public ProduktController(TheBreadPitContext context, IWebHostEnvironment environment)
        {
            this.context = context;
            _environment = environment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var categorien = context.Categorien.OrderBy(x => x.CategoryID).ToList();
            Produkt? produkt = context.Produkten.Find(id);
            var categoryNaam = "";

            foreach (var category in categorien)
            {
                if (category.CategoryID == produkt?.CategoryID)
                {
                    categoryNaam = category.CategorieNaam;
                }
            }

            string fileName = $"{produkt?.ProduktNaam.Replace(" ", "")}.jpeg";
            string webImagePath = $"/images/Produkten/{fileName}";

            string physicalPath = Path.Combine(_environment.WebRootPath, "images", "Produkten", fileName);
            if (!System.IO.File.Exists(physicalPath))
            {
                webImagePath = "/images/Produkten/thebreadpit.jpeg"; 
            }

            ViewBag.ImagePath = webImagePath;

            return View(produkt);
        }


        [Route("[area]/Categorien/{id?}")]
        public IActionResult List(int? id) 
        {
            var categorien = context.Categorien.OrderBy(c => c.CategoryID).ToList();
            IQueryable<Produkt> query = context.Produkten;

            if (id.HasValue)
            {
                query = query.Where(p => p.CategoryID == id.Value);
            }
            else
            {
                query = query.Where(p => true); 
            }

            var produkten = query.OrderBy(x => x.ProductID).ToList();

            var list = new ProduktenLijst
            {
                Produkten = produkten,
                Categorien = categorien,
                SelectedCategory = id.HasValue ? categorien.FirstOrDefault(c => c.CategoryID == id.Value)?.CategorieNaam : "Alles"
            };

            return View(list);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using The_Bread_Pit.Models;

namespace The_Bread_Pit.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            // Zorgt ervoor dat een sessie-ID wordt gegenereerd en bewaard
            HttpContext.Session.SetString("Init", "1"); 
            return View();
        }

        [Route("action")]
        public IActionResult About()
        {
            return View();
        }

    }
}

Areas/User/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Welkom bij The Bread Pit!";
}

<h1></h1>
<div class="container">
    <div class="text-center">
        <h1 class="display-4">Frisse en Heerlijke Broodjes, Elke Dag!</h1>
        <h4 class="lead">Ontdek onze lekkere broodjes, zoete lekkernijen en hapjes met een drankje.</h4>
        <hr class="my-5">
        <p>Blader door onze selectie en bestel met gemak je favorieten.</p>
        <a class="btn btn-primary btn-lg" style="width: 40%" asp-controller="Produkt" asp-action="List" role="button"> Klik hier om verder te gaan </a>
    </div>
</div>

<div class="row justify-content-center mt-5">
    <div class="col-md-1"></div>
    <a asp-area="User" asp-controller="Produkt" asp-action="List" asp-route-id="@(5)" class="col-md-3 mb-3">
        <div class="card shadow-sm">
            <img src="~/images/belegde broodjes2.jpg" class="card-img-top" alt="Lekkere broodjes">
            <div class="card-body">
                <p class="card-text text-center">Lekkere broodjes</p>
            </div>
        </div>
    </a>
    <a asp-area="User" asp-controller="Produkt" asp-action="List" asp-route-id="@(1)" class="col-md-3 mb-3">
        <div class="card shadow-sm">
            <img src="~/images/Soep.jpg" class="bd-placeholder-img card-img-top" alt="Soep">
            <div class="card-body">
                <p class="card-text text-center">Soep</p>
            </div>
        </div>
    </a>
    <a asp-area="User" asp-controller="Produkt" asp-action="List" asp-route-id="@(3)" class="col-md-3 mb-3">
            <div class="card shadow-sm">
            <img src="~/images/Pasta.jpg" class="bd-placeholder-img card-img-top"  alt="Pasta">
            <div class="card-body">
                <p class="card-text text-center">Pasta</p>
            </div>
        </div>
    </a>
    <div class="col-md-1"></div>
</div>
<div class="row justify-content-center">
    <div class="col-md-1"></div>
    <a asp-area="User" asp-controller="Produkt" asp-action="List" asp-route-id="@(6)" class="col-md-3 mb-3">
        <div class="card shadow-sm">
            <img src="~/images/zoet-fruit.jpg" class="bd-placeholder-img card-img-top" alt="Fruit & gebak">
            <div class="card-body">
                <p class="card-text text-center">Fruit & gebak</p>
            </div>
        </div>
    </a>
    <a asp-area="User" asp-controller="Produkt" asp-action="List" asp-route-id="@(8)" class="col-md-3 mb-3">
        <div class="card shadow-sm">
            <img src="~/images/Dranken.jpg" class="bd-placeholder-img card-img-top" alt="Dranken">
            <div class="card-body">
                <p class="card-text text-center">Dranken</p>
            </div>
        </div>
    </a>
    <a asp-area="User" asp-controller="Produkt" asp-action="List" asp-route-id="@(7)" class="col-md-3 mb-3">
        <div class="card shadow-sm">
            <img src="~/images/Andere.jpg" class="bd-placeholder-img card-img-top" alt="Andere">
            <div class="card-body">
                <p class="card-text text-center">Andere</p>
            </div>
    </div>
    </a>
    <div class="col-md-1"></div>
</div>

@section Scripts {
    <script>
        // Eventuele scripts die nodig zijn voor de pagina
    </script>
}